### ISSUE TITLE
high coupling i abstractOwnable 

### ISSUE THREAD

**Issue by Carzita** [evil-morfar/Matador_3#4]
Det strider imod low coupling, at abstractOwnable har direkte adgang til player klassen (protected player owner, linje 13). Hvis muligt burde det ændres så abstractOwnable får adgang til player klassen via controlleren og ikke direkte

**Comment by evil-morfar** [comment]
Det gør vel kun koblingen højere af den også skal være afhængig af controlleren? Den har jo ikke direkte adgang, den får bare leveret et objekt af typen `Player`. Player bør dog være `private`.
